### ISSUE TITLE
Things to add

### ISSUE THREAD

**Issue by sam-grierson** [sam-grierson/Group-Project#1]
**Some things to add to the page:**

- Better CSS
- Product Search
- Email/Contact
- Web Admin Page
- Checkout

**Comment by Fiftyllama** [comment]
I'll add all issues separately, that way we can more easily split stuff up

**Comment by 0xMo** [comment]
Perfect

**Comment by Fiftyllama** [comment]
I fixed some of this in a pull request I made earlier, the problem was at least partly connected to issue #7

**Comment by sam-grierson** [comment]
Sweet, I'll close this and we can use the separate issues.
