### ISSUE TITLE
price not shown even though database has a price listed

### ISSUE THREAD

**Issue by Fiftyllama** [sam-grierson/Group-Project#10]
not quite sure whats causing this, had a slight glance but couldnt suss it. potentially a type missmatch between sqlite floats and js floats

**Comment by sam-grierson** [comment]
Figured it out, the price in the database was capitalised and in the code the object name for price was lower case "p". I changed over the code to match the new database.

**Comment by Fiftyllama** [comment]
Sweet, reffence this issue in the commit comment and I'll close it
