### ISSUE TITLE
Disappearing product images after an item is removed from the cart

### ISSUE THREAD

**Issue by sam-grierson** [sam-grierson/Group-Project#11]
Totally lost on this one. After an item is removed from the cart the items in the session are re-rendered into the cart but they seem to lose their path to the image, every other value seems to be correct on the page render as far as I can tell.

**Comment by Fiftyllama** [comment]
Are you sure your not removing the entries from the database?

**Comment by sam-grierson** [comment]
Should only be removing them from the users cart object in their session

**Comment by sam-grierson** [comment]
re-rendering out the page cause the image paths to break for some reason,  changed it to just redirect to the cart page which has fixed the issue.
