### ISSUE TITLE
New login and registration in nav bar. Should the old views just be removed?

### ISSUE THREAD

**Issue by sam-grierson** [sam-grierson/Group-Project#13]
With the updated nav bar should we just remove the old login and registration pages? Also I was thinking we could group login and registration under the little person icon on the right of the nav bar and use a dropdown with links to them and maybe a user profile page where they can change their details?

**Comment by 0xMo** [comment]
Its sounds good to put the login/registration under the the person icon!
I think we if we are going to use the updated one we should remove the old pages

**Comment by 0xMo** [comment]
the drop-down button of the person icon have been made, which this issue could be closed
