### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by Fiftyllama** [sam-grierson/Group-Project#6]
we need to add a checkout, this could probably also just be nice looking html since the degree we're actually gonna hook it up (obvs we're not taking payments)

**Comment by sam-grierson** [comment]
I agree. The only functionality it really needs is maybe something saying that your order is on the way and clearing your cart. Its possible we could add a user profile page which shows current orders as shipping but that could be a low piority for now.

**Comment by sam-grierson** [comment]
Added a sort of place holder checkout view and route, it should check if the cart is empty and if the user is logged in, still needs forms and probably some css. I was thinking we could have the users with accounts put their details in some kind of profile page and then the checkout would ask them to confirm the details. Going to be a bit of database work on the back end though (maybe even a table that holds the users current orders and shows them on their profile page).

**Comment by sam-grierson** [comment]
Checkout's basically finished. Let me know what you guys think, there's probably some stuff that can be improved on.

**Comment by sam-grierson** [comment]
Checkout is functionally complete, only a few minor changes to the visuals will be made so I'm closing this for now. Any bugs can be opened as their own issue.
